sonar.projectKey=github-sonar-demo
sonar.projectName=github-sonar-demo
sonar.sources=.
sonar.host.url=https://margareta-baccivorous-metonymically.ngrok-free.dev 
sonar.login=sqa_3ba0862506c5188fa917d3ca8a89c03755eda7e1
